import { Bot, FileText, GitBranch, House, MessagesSquare, Package, Tags, Truck } from 'lucide-react';
import { AutomationAction, IntegrationPlatform, ProductSource } from './types/api';

export const navLinks = [
  { id: 1, name: 'Dashboard', path: '/app/dashboard', icon: House, translationTag: 'dashboard.title' },
  { id: 2, name: 'Orders', path: '/app/orders', icon: Package, translationTag: 'orders.title' },
  { id: 3, name: 'Products', path: '/app/products', icon: Tags, translationTag: 'products.title' },
  { id: 4, name: 'Invoices', path: '/app/invoices', icon: FileText, translationTag: 'invoices.title' },
  { id: 5, name: 'Integrations', path: '/app/integrations', icon: GitBranch, translationTag: 'integrations.title' },
  { id: 6, name: 'Automations', path: '/app/automations', icon: GitBranch, translationTag: 'automations.title' },
];
export type ColorScheme = keyof typeof colorSchemes;

export const colorSchemes = {
  blue: {
    bg: 'bg-blue-500',
    bgHover: 'hover:bg-blue-600',
    bgLight: 'bg-blue-100',
    bgDark: 'bg-blue-900',
    text: 'text-blue-500',
    textHover: 'hover:text-blue-600',
    textLight: 'text-blue-100',
    textDark: 'text-blue-900',
    border: 'border-blue-500',
    borderHover: 'hover:border-blue-600',
    shadow: 'shadow-blue-500/50',
    ring: 'ring-blue-500',
    gradient: 'from-blue-500 to-blue-600',
    gradientHover: 'hover:from-blue-600 hover:to-blue-700',
  },
  indigo: {
    bg: 'bg-indigo-500',
    bgHover: 'hover:bg-indigo-600',
    bgLight: 'bg-indigo-100',
    bgDark: 'bg-indigo-900',
    text: 'text-indigo-500',
    textHover: 'hover:text-indigo-600',
    textLight: 'text-indigo-100',
    textDark: 'text-indigo-900',
    border: 'border-indigo-500',
    borderHover: 'hover:border-indigo-600',
    shadow: 'shadow-indigo-500/50',
    ring: 'ring-indigo-500',
    gradient: 'from-indigo-500 to-indigo-600',
    gradientHover: 'hover:from-indigo-600 hover:to-indigo-700',
  },
  sky: {
    bg: 'bg-sky-500',
    bgHover: 'hover:bg-sky-600',
    bgLight: 'bg-sky-100',
    bgDark: 'bg-sky-900',
    text: 'text-sky-500',
    textHover: 'hover:text-sky-600',
    textLight: 'text-sky-100',
    textDark: 'text-sky-900',
    border: 'border-sky-500',
    borderHover: 'hover:border-sky-600',
    shadow: 'shadow-sky-500/50',
    ring: 'ring-sky-500',
    gradient: 'from-sky-500 to-sky-600',
    gradientHover: 'hover:from-sky-600 hover:to-sky-700',
  },
  red: {
    bg: 'bg-red-500',
    bgHover: 'hover:bg-red-600',
    bgLight: 'bg-red-100',
    bgDark: 'bg-red-900',
    text: 'text-red-500',
    textHover: 'hover:text-red-600',
    textLight: 'text-red-100',
    textDark: 'text-red-900',
    border: 'border-red-500',
    borderHover: 'hover:border-red-600',
    shadow: 'shadow-red-500/50',
    ring: 'ring-red-500',
    gradient: 'from-red-500 to-red-600',
    gradientHover: 'hover:from-red-600 hover:to-red-700',
  },
  green: {
    bg: 'bg-green-500',
    bgHover: 'hover:bg-green-600',
    bgLight: 'bg-green-100',
    bgDark: 'bg-green-900',
    text: 'text-green-500',
    textHover: 'hover:text-green-600',
    textLight: 'text-green-100',
    textDark: 'text-green-900',
    border: 'border-green-500',
    borderHover: 'hover:border-green-600',
    shadow: 'shadow-green-500/50',
    ring: 'ring-green-500',
    gradient: 'from-green-500 to-green-600',
    gradientHover: 'hover:from-green-600 hover:to-green-700',
  },
  yellow: {
    bg: 'bg-yellow-500',
    bgHover: 'hover:bg-yellow-600',
    bgLight: 'bg-yellow-100',
    bgDark: 'bg-yellow-900',
    text: 'text-yellow-500',
    textHover: 'hover:text-yellow-600',
    textLight: 'text-yellow-100',
    textDark: 'text-yellow-900',
    border: 'border-yellow-500',
    borderHover: 'hover:border-yellow-600',
    shadow: 'shadow-yellow-500/50',
    ring: 'ring-yellow-500',
    gradient: 'from-yellow-500 to-yellow-600',
    gradientHover: 'hover:from-yellow-600 hover:to-yellow-700',
  },
  teal: {
    bg: 'bg-teal-500',
    bgHover: 'hover:bg-teal-600',
    bgLight: 'bg-teal-100',
    bgDark: 'bg-teal-900',
    text: 'text-teal-500',
    textHover: 'hover:text-teal-600',
    textLight: 'text-teal-100',
    textDark: 'text-teal-900',
    border: 'border-teal-500',
    borderHover: 'hover:border-teal-600',
    shadow: 'shadow-teal-500/50',
    ring: 'ring-teal-500',
    gradient: 'from-teal-600 to-cyan-400',
    gradientHover: 'hover:from-teal-600 hover:to-teal-700',
  },
  purple: {
    bg: 'bg-purple-500',
    bgHover: 'hover:bg-purple-600',
    bgLight: 'bg-purple-100',
    bgDark: 'bg-purple-900',
    text: 'text-purple-500',
    textHover: 'hover:text-purple-600',
    textLight: 'text-purple-100',
    textDark: 'text-purple-900',
    border: 'border-purple-500',
    borderHover: 'hover:border-purple-600',
    shadow: 'shadow-purple-500/50',
    ring: 'ring-purple-500',
    gradient: 'from-purple-500 to-purple-600',
    gradientHover: 'hover:from-purple-600 hover:to-purple-700',
  },
  orange: {
    bg: 'bg-orange-500',
    bgHover: 'hover:bg-orange-600',
    bgLight: 'bg-orange-100',
    bgDark: 'bg-orange-900',
    text: 'text-orange-500',
    textHover: 'hover:text-orange-600',
    textLight: 'text-orange-100',
    textDark: 'text-orange-900',
    border: 'border-orange-500',
    borderHover: 'hover:border-orange-600',
    shadow: 'shadow-orange-500/50',
    ring: 'ring-orange-500',
    gradient: 'from-orange-600 to-orange-400',
    gradientHover: 'hover:from-orange-600 hover:to-orange-700',
  },
  gray: {
    bg: 'bg-gray-500',
    bgHover: 'hover:bg-gray-600',
    bgLight: 'bg-gray-100',
    bgDark: 'bg-gray-900',
    text: 'text-gray-500',
    textHover: 'hover:text-gray-600',
    textLight: 'text-gray-100',
    textDark: 'text-gray-900',
    border: 'border-gray-500',
    borderHover: 'hover:border-gray-600',
    shadow: 'shadow-gray-500/50',
    ring: 'ring-gray-500',
    gradient: 'from-gray-500 to-gray-600',
    gradientHover: 'hover:from-gray-600 hover:to-gray-700',
  },
};

export type AppIntegration = {
  id: number;
  name: string;
  scheme: string;
  type: string;
  platform: IntegrationPlatform;
  description: string;
  link?: string;
};

export const appIntegrations = [
  {
    id: 1,
    name: 'Allegro',
    scheme: 'orange',
    type: 'link',
    platform: IntegrationPlatform.ALLEGRO,
    description: 'Connect your Allegro account to manage orders and inventory directly from your dashboard',
    link: `https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=3916151b9e8a49c3987ea9428ff8cf75&redirect_uri=https://mag2-web-production.up.railway.app/app/integrations/middleware`,
  },
  {
    id: 2,
    name: 'Fakturowo',
    scheme: 'blue',
    type: 'api_key',
    platform: IntegrationPlatform.FAKTUROWO,
    description: 'Integrate with Fakturowo to automate your invoicing and accounting processes',
  },
  {
    id: 3,
    name: 'Erli',
    scheme: 'blue',
    type: 'api_key',
    platform: IntegrationPlatform.ERLI,
    description: 'Integrate with Fakturowo to automate your invoicing and accounting processes',
  },
  {
    id: 4,
    name: 'EmpikPlace',
    scheme: 'gray',
    type: 'api_key',
    platform: IntegrationPlatform.EMPIK,
    description: 'Integrate with Empik to automate your invoicing and accounting processes',
  },
];

export const automationActionsByIntegration = {
  [IntegrationPlatform.FAKTUROWO]: [AutomationAction.GENERATE_INVOICE, AutomationAction.CONNECT_INVOICE],
  [IntegrationPlatform.ALLEGRO]: [
    AutomationAction.SEND_UPSELL_MESSAGE,
    AutomationAction.SEND_PAYMENT_REMINDER_MESSAGE,
    AutomationAction.UPDATE_ORDER_TRACKING_STATUS,
    AutomationAction.AUTORESPONDER,
  ],
  [IntegrationPlatform.ERLI]: [
    AutomationAction.SEND_UPSELL_MESSAGE,
    AutomationAction.SEND_PAYMENT_REMINDER_MESSAGE,
    AutomationAction.UPDATE_ORDER_TRACKING_STATUS,
    AutomationAction.AUTORESPONDER,
  ],
  [IntegrationPlatform.VINTED]: [
    AutomationAction.SEND_UPSELL_MESSAGE,
    AutomationAction.SEND_PAYMENT_REMINDER_MESSAGE,
    AutomationAction.UPDATE_ORDER_TRACKING_STATUS,
    AutomationAction.AUTORESPONDER,
  ],
};

export const automationsActions = [
  {
    id: 1,
    name: 'Upsell Messages',
    description: 'Automatically send personalized upsell messages to customers after their purchase to increase average order value',
    icon: MessagesSquare,
    action: AutomationAction.SEND_UPSELL_MESSAGE,
    translationKey: 'automations.actions.upsellMessage',
    isBeta: false,
    isNew: false,
    scheme: 'yellow',
    tags: ['messages'],
  },
  {
    id: 2,
    name: 'Payment Reminder Messages',
    description: "Send automated payment reminder messages to customers who haven't completed their payment within the specified timeframe",
    icon: MessagesSquare,
    action: AutomationAction.SEND_PAYMENT_REMINDER_MESSAGE,
    translationKey: 'automations.actions.paymentReminderMessage',
    isBeta: false,
    isNew: false,
    scheme: 'yellow',
    tags: ['messages'],
  },
  {
    id: 3,
    name: 'Generate Invoice',
    description: 'Automatically generate invoices for completed orders with customizable templates and branding',
    icon: FileText,
    action: AutomationAction.GENERATE_INVOICE,
    translationKey: 'automations.actions.generateInvoice',
    isBeta: false,
    isNew: false,
    scheme: 'blue',
    tags: ['marketplace'],
  },
  {
    id: 4,
    name: 'Send invoice to buyer',
    description: 'Automatically send generated invoices to buyers via email or platform messaging system',
    icon: FileText,
    action: AutomationAction.CONNECT_INVOICE,
    translationKey: 'automations.actions.connectInvoice',
    isBeta: false,
    isNew: false,
    scheme: 'yellow',
    tags: ['invoicing'],
  },
  {
    id: 5,
    name: 'Update Order Status by Tracking',
    description: 'Automatically update order status based on tracking information from shipping carriers',
    icon: Truck,
    action: AutomationAction.UPDATE_ORDER_TRACKING_STATUS,
    translationKey: 'automations.actions.updateTracking',
    isBeta: true,
    isNew: true,
    scheme: 'indigo',
    tags: ['marketplace'],
  },
  {
    id: 6,
    name: 'Auto Responder',
    description: 'Set up automated responses to common customer inquiries and messages across your sales platforms',
    icon: Bot,
    action: AutomationAction.AUTORESPONDER,
    translationKey: 'automations.actions.autoresponder',
    isBeta: false,
    isNew: true,
    scheme: 'purple',
    tags: ['messages'],
  },
  {
    id: 6,
    name: 'Stock Synchronizer',
    description: 'Automatically synchronize product stock levels across all connected sales channels to prevent overselling and ensure inventory accuracy',
    icon: Bot,
    action: AutomationAction.ORCHESTRATOR,
    translationKey: 'automations.actions.stockOrchestrator',
    isBeta: true,
    isNew: true,
    scheme: 'blue',
    tags: ['marketplace'],
  },
];

export const currencies = [
  { id: 1, code: 'PLN', flag: '🇵🇱', translationTag: 'currencies.pln' },
  { id: 2, code: 'EUR', flag: '🇪🇺', translationTag: 'currencies.eur' },
  { id: 3, code: 'USD', flag: '🇺🇸', translationTag: 'currencies.usd' },
  { id: 4, code: 'GBP', flag: '🇬🇧', translationTag: 'currencies.gbp' },
  { id: 5, code: 'CHF', flag: '🇨🇭', translationTag: 'currencies.chf' },
  { id: 6, code: 'JPY', flag: '🇯🇵', translationTag: 'currencies.jpy' },
  { id: 7, code: 'CAD', flag: '🇨🇦', translationTag: 'currencies.cad' },
  { id: 8, code: 'AUD', flag: '🇦🇺', translationTag: 'currencies.aud' },
  { id: 9, code: 'CNY', flag: '🇨🇳', translationTag: 'currencies.cny' },
  { id: 10, code: 'CZK', flag: '🇨🇿', translationTag: 'currencies.czk' },
  { id: 11, code: 'HUF', flag: '🇭🇺', translationTag: 'currencies.huf' },
];

export const logos: Record<IntegrationPlatform, string> = {
  ALLEGRO: 'https://companieslogo.com/img/orig/ALE.WA-05f5159c.png?t=1720244490',
  DPD: '',
  EMPIK: '',
  ERLI: 'https://assets.appmeme.com/pl.erli.app--128-icon.png',
  FAKTUROWO: '',
  INPOST: '',
  VINTED: '',
};

export const MARKETPLACES: Record<ProductSource, { id: number; scheme: ColorScheme; title: string; value: string; description: string; logo: string }> = {
  ALLEGRO: {
    id: 1,
    scheme: 'orange',
    title: 'Allegro',
    value: 'allegro',
    description: '',
    logo: logos['ALLEGRO'],
  },
  ERLI: {
    id: 2,
    scheme: 'teal',
    description: '',
    logo: logos['ERLI'],
    title: 'Erli',
    value: 'erli',
  },
  EMPIK: {
    id: 3,
    scheme: 'gray',
    description: '',
    logo: logos['EMPIK'],
    title: 'EmpikPlace',
    value: 'empik',
  },
};
